// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tskKM7gWsfxPWKdeF2whbc
// Component: L9QGF6sCVLj5k
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: LEk1Ms6W7FfOq/component
import ProductCarousel from "../../ProductCarousel"; // plasmic-import: X788gSiuU8KF8X/component
import ProductCard from "../../ProductCard"; // plasmic-import: icNUD1hnFNqGm5/component
import Ratings from "../../Ratings"; // plasmic-import: IurJu888QF07I_/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: Dm2XEDwRPZegl/component
import BlogPost from "../../BlogPost"; // plasmic-import: qEjY_mf51k0AtM/component
import Footer from "../../Footer"; // plasmic-import: D6IBayx2f-xL4/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: hV3L_lmmVvrCbl/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: tskKM7gWsfxPWKdeF2whbc/projectcss
import * as sty from "./PlasmicHome.module.css"; // plasmic-import: L9QGF6sCVLj5k/css

export type PlasmicHome__VariantMembers = {};

export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  productCarousel?: p.Flex<typeof ProductCarousel>;
  featureItem?: p.Flex<typeof FeatureItem>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultHomeProps {
  className?: string;
}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
      </Head>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div className={classNames(defaultcss.all, sty.box___3Oz5Y)}>
            <Header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames("__wab_instance", sty.header)}
            />

            <ProductCarousel
              data-plasmic-name={"productCarousel"}
              data-plasmic-override={overrides.productCarousel}
              className={classNames("__wab_instance", sty.productCarousel)}
            />

            <div className={classNames(defaultcss.all, sty.box__oEhs0)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__e8WuE
                )}
              >
                {"New Arrivals"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__jwlpl)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard___2FeK)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__lylay)}
                    role={"img"}
                    src={"/plasmic/furn_e_commerce/images/arrivals1.png"}
                  />
                }
                onSale={"onSale" as const}
                price={"$65.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__zCHlg)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Wooden Chair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__pwp5X)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___5A3Ko)}
                    role={"img"}
                    src={"/plasmic/furn_e_commerce/images/arrivals2.png"}
                  />
                }
                onSale={"onSale" as const}
                price={"$80.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__nsuBn)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Single Armchair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__fumab)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__jkMvF)}
                    role={"img"}
                    src={"/plasmic/furn_e_commerce/images/arrivals3.png"}
                  />
                }
                price={"$40.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__aVxC7)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Wooden Armchair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__ywUJ)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__tzHxR)}
                    role={"img"}
                    src={"/plasmic/furn_e_commerce/images/arrivals4.png"}
                  />
                }
                onSale={"onSale" as const}
                price={"$100.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings___8DFr)}
                    numReviews={"(45 Review)"}
                  />
                }
                title={"Stylish Chair"}
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__j8Wk3)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__mb6U)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__iSs78)}
                    role={"img"}
                    src={"/plasmic/furn_e_commerce/images/arrivals5.png"}
                  />
                }
                price={"$120.00"}
                title={"Modern Chair"}
              />

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___9PjjV
                )}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__kyjTm)}
                    role={"img"}
                    src={"/plasmic/furn_e_commerce/images/arrivals6.png"}
                  />
                }
                onSale={"onSale" as const}
                price={"$140.00"}
                title={"Mapple Wood Dinning Table"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__laFxv)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__cvtH5)}
                    role={"img"}
                    src={"/plasmic/furn_e_commerce/images/arrivals7.png"}
                  />
                }
                onSale={"onSale" as const}
                price={"$90.00"}
                title={"Arm Chair"}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__ariVq)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__sjWg)}
                    role={"img"}
                    src={"/plasmic/furn_e_commerce/images/arrivals8.png"}
                  />
                }
                price={"$140.00"}
                title={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___6PrhN
                    )}
                  >
                    {"Wooden Bed"}
                  </div>
                }
              />
            </p.Stack>

            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div className={classNames(defaultcss.all, sty.box__fyB7I)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__yhd7E
                )}
              >
                {"Featured Products"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__gmQ0D)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__ckXip)}
                price={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__dawgZ
                    )}
                  >
                    {"$160.00"}
                  </div>
                }
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__bHCi5)}
                    numReviews={"(12 Review)"}
                    stars={"two" as const}
                  />
                }
                title={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__ksem
                    )}
                  >
                    {"Designed Sofa"}
                  </div>
                }
                withReviews={"withReviews" as const}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__iTRw8)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__bHx4)}
                    role={"img"}
                    src={"/plasmic/furn_e_commerce/images/f2.jpeg"}
                  />
                }
                price={"$200.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__zcvZv)}
                    stars={"four" as const}
                  />
                }
                title={"Dining Table"}
                withReviews={"withReviews" as const}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__gt9JV)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___9SgV5)}
                    role={"img"}
                    src={"/plasmic/furn_e_commerce/images/f3.jpeg"}
                  />
                }
                price={"$100.00"}
                ratings={
                  <Ratings
                    className={classNames("__wab_instance", sty.ratings__dt2Xc)}
                    numReviews={"(23 Review)"}
                    stars={"five" as const}
                  />
                }
                title={"Chair and Table"}
                withReviews={"withReviews" as const}
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard___6Ssa)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___3FoOq)}
                    role={"img"}
                    src={"/plasmic/furn_e_commerce/images/f4.jpeg"}
                  />
                }
                price={"$299.00"}
                ratings={
                  <Ratings
                    className={classNames(
                      "__wab_instance",
                      sty.ratings___1XOjT
                    )}
                    numReviews={"(35 Review)"}
                  />
                }
                title={"Modern Arm Chair"}
                withReviews={"withReviews" as const}
              />
            </p.Stack>

            <div className={classNames(defaultcss.all, sty.box__ma7PQ)}>
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__i0Gy9
                )}
              >
                {"Latest Blog"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__jwofu)}
            >
              <BlogPost
                className={classNames("__wab_instance", sty.blogPost__h9LeL)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__tcTSr)}
                    role={"img"}
                    src={"/plasmic/furn_e_commerce/images/b1.jpeg"}
                  />
                }
              />

              <BlogPost
                className={classNames("__wab_instance", sty.blogPost__g28Qs)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__owgRa)}
                    role={"img"}
                    src={"/plasmic/furn_e_commerce/images/b2.jpeg"}
                  />
                }
              />

              <BlogPost
                className={classNames("__wab_instance", sty.blogPost__mzvxH)}
                image={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___5T2Mp)}
                    role={"img"}
                    src={"/plasmic/furn_e_commerce/images/b3.jpeg"}
                  />
                }
              />
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__cPkyA)}
            >
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___2M2E)}
                role={"img"}
                src={"/plasmic/furn_e_commerce/images/adidas.png"}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__fqRar)}
                role={"img"}
                src={"/plasmic/furn_e_commerce/images/hm.png"}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__dxhEm)}
                role={"img"}
                src={"/plasmic/furn_e_commerce/images/kappa.png"}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__dilwt)}
                role={"img"}
                src={"/plasmic/furn_e_commerce/images/lacoste.png"}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__k1P4S)}
                role={"img"}
                src={"/plasmic/furn_e_commerce/images/levis.png"}
              />
            </p.Stack>

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "productCarousel", "featureItem", "footer"],
  header: ["header"],
  productCarousel: ["productCarousel"],
  featureItem: ["featureItem"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  productCarousel: typeof ProductCarousel;
  featureItem: typeof FeatureItem;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicHome__VariantsArgs;
  args?: PlasmicHome__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicHome__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicHome__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    productCarousel: makeNodeComponent("productCarousel"),
    featureItem: makeNodeComponent("featureItem"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
